version: '2'
services:
    pagansampleapp-app:
        image: pagansampleapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pagansampleapp-mysql:3306/pagansampleapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pagansampleapp-mysql:
        extends:
            file: mysql.yml
            service: pagansampleapp-mysql
